version: '3'

service:
  blogpy__postgresql:
    image: postgres:12
    container_name: blogpy_postgresql
    volume:
      - blogpy_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - blogpy_network

volume:
  blogpy_postgresql:
    external: true
networks:
  blogpy_network:
    external: true